import type { HistoricalAnchor } from './types';

type AnchorInput = Omit<HistoricalAnchor,
  'status' | 'pressure' | 'lastEvaluatedAt' | 'proposedAt' | 'activatedAt' | 'manifestedAt' | 'manifestation' | 'dossierId'>;

const anchor = (input: AnchorInput): HistoricalAnchor => ({
  ...input,
  status: 'dormant',
  pressure: input.basePressure,
});

/**
 * Bibliothèque des ancrages historiques de la première période jouable.
 * Ils ne sont pas des rails narratifs : chacun décrit une pression, une
 * fenêtre, des invariants et plusieurs manifestations admissibles.
 */
export const historicalAnchors2000: Record<string, HistoricalAnchor> = {
  'russia-recentralization': anchor({
    id: 'russia-recentralization', title: 'Recentrage du pouvoir russe',
    trendTitle: 'Retour de l’autorité centrale russe',
    trendSummary: 'Le pouvoir exécutif russe cherche à reprendre le contrôle de l’appareil d’État, des régions et des grands intérêts économiques.',
    kind: 'power_struggle', importance: 'major', probableWindow: { start: '2000-01-01', end: '2004-12-31' },
    proposalThreshold: 48, activationThreshold: 74, basePressure: 66, historicalWeight: 92,
    affectedActors: ['RUS', 'USA', 'FRA', 'DEU', 'POL'], regionTags: ['Europe', 'Eurasie'],
    invariants: ['Renforcement progressif de l’exécutif fédéral', 'Réduction de l’autonomie des oligarques et des régions'],
    possibleManifestations: ['Consolidation présidentielle', 'Crise avec un oligarque', 'Réforme administrative centralisatrice'],
    playerVisibility: 'known', playerInfluence: 'medium',
  }),
  'china-wto-integration': anchor({
    id: 'china-wto-integration', title: 'Entrée de la Chine dans l’OMC',
    trendTitle: 'Intégration industrielle et commerciale de la Chine',
    trendSummary: 'La Chine devient progressivement un centre industriel mondial et augmente sa dépendance aux marchés, technologies et capitaux étrangers.',
    kind: 'economic', importance: 'major', trendId: 'china-industrial-rise', probableWindow: { start: '2000-01-01', end: '2003-12-31' },
    proposalThreshold: 52, activationThreshold: 78, basePressure: 72, historicalWeight: 96,
    affectedActors: ['CHN', 'USA', 'DEU', 'FRA', 'JPN', 'IND'], regionTags: ['Asie de l’Est', 'Amérique du Nord', 'Europe'],
    invariants: ['Ouverture accrue des échanges chinois', 'Accélération de la concurrence industrielle mondiale'],
    possibleManifestations: ['Accession commerciale formelle', 'Afflux d’investissements', 'Premières tensions protectionnistes'],
    playerVisibility: 'known', playerInfluence: 'low',
  }),
  'mass-casualty-terrorism': anchor({
    id: 'mass-casualty-terrorism', title: 'Attentat terroriste de grande ampleur',
    trendTitle: 'Montée d’une menace terroriste transnationale',
    trendSummary: 'Des réseaux clandestins acquièrent une capacité opérationnelle inhabituelle et cherchent une opération extérieure à fort impact.',
    kind: 'security', importance: 'critical', trendId: 'transnational-jihadism', probableWindow: { start: '2001-01-01', end: '2003-12-31' },
    proposalThreshold: 54, activationThreshold: 82, basePressure: 58, historicalWeight: 100,
    affectedActors: ['USA', 'GBR', 'FRA', 'RUS', 'PAK', 'AFG'], regionTags: ['Amérique du Nord', 'Moyen-Orient', 'Asie du Sud'],
    invariants: ['Opération préparée par un réseau transnational', 'Réponse sécuritaire et militaire internationale'],
    possibleManifestations: ['Attentat coordonné contre une infrastructure', 'Tentative d’attentat déjouée', 'Série d’attaques de moindre ampleur'],
    playerVisibility: 'suspected', playerInfluence: 'medium',
  }),
  'iraq-intervention': anchor({
    id: 'iraq-intervention', title: 'Intervention internationale en Irak',
    trendTitle: 'Volonté américaine de remodelage du Moyen-Orient',
    trendSummary: 'Washington débat d’une opération visant à renverser le régime irakien, avec des conséquences régionales difficiles à maîtriser.',
    kind: 'conflict', importance: 'major', probableWindow: { start: '2002-01-01', end: '2004-12-31' },
    proposalThreshold: 56, activationThreshold: 79, basePressure: 59, historicalWeight: 91,
    affectedActors: ['USA', 'GBR', 'FRA', 'RUS', 'TUR', 'IRN'], regionTags: ['Moyen-Orient', 'Europe', 'Amérique du Nord'],
    invariants: ['Pression américaine sur le régime irakien', 'Risque de déstabilisation régionale'],
    possibleManifestations: ['Invasion terrestre', 'Ultimatum prolongé', 'Coalition internationale limitée', 'Retrait diplomatique européen'],
    playerVisibility: 'known', playerInfluence: 'high',
  }),
  'eastern-enlargement': anchor({
    id: 'eastern-enlargement', title: 'Élargissement de l’UE et de l’OTAN vers l’Est',
    trendTitle: 'Extension de l’espace politique et sécuritaire occidental',
    trendSummary: 'Les États d’Europe centrale et orientale cherchent des garanties occidentales, tandis que la Russie y voit une perte d’influence stratégique.',
    kind: 'cooperation', importance: 'major', probableWindow: { start: '2003-01-01', end: '2007-12-31' },
    proposalThreshold: 48, activationThreshold: 75, basePressure: 63, historicalWeight: 97,
    affectedActors: ['POL', 'DEU', 'FRA', 'GBR', 'RUS', 'USA', 'CZE', 'HUN', 'ROU', 'BGR'], regionTags: ['Europe', 'Eurasie'],
    invariants: ['Demandes d’ancrage occidental des nouveaux membres', 'Réaction russe à l’évolution de l’équilibre européen'],
    possibleManifestations: ['Adhésions formelles', 'Accords de défense transitoires', 'Coalition de prudence face à Moscou'],
    playerVisibility: 'known', playerInfluence: 'medium',
  }),
  'russia-georgia-war': anchor({
    id: 'russia-georgia-war', title: 'Guerre russo-géorgienne',
    trendTitle: 'Première confrontation armée entre la Russie et un voisin soutenu par l’Occident',
    trendSummary: 'Les tensions territoriales et l’élargissement des garanties occidentales rendent un affrontement dans le Caucase plausible.',
    kind: 'conflict', importance: 'major', probableWindow: { start: '2007-01-01', end: '2009-12-31' },
    proposalThreshold: 58, activationThreshold: 82, basePressure: 52, historicalWeight: 83,
    affectedActors: ['RUS', 'USA', 'FRA', 'DEU', 'TUR'], regionTags: ['Eurasie', 'Europe'],
    invariants: ['Tension autour de territoires séparatistes', 'Dilemme occidental entre soutien et escalade'],
    possibleManifestations: ['Guerre courte', 'Crise armée contenue', 'Accord de sécurité négocié'],
    playerVisibility: 'known', playerInfluence: 'medium',
  }),
  'global-financial-crisis': anchor({
    id: 'global-financial-crisis', title: 'Crise financière mondiale',
    trendTitle: 'Fragilité systémique du crédit et des marchés',
    trendSummary: 'L’endettement, la titrisation et la concentration des risques bancaires créent une vulnérabilité mondiale.',
    kind: 'economic', importance: 'critical', trendId: 'global-financial-fragility', probableWindow: { start: '2007-01-01', end: '2010-12-31' },
    proposalThreshold: 50, activationThreshold: 78, basePressure: 62, historicalWeight: 100,
    affectedActors: ['USA', 'GBR', 'DEU', 'FRA', 'ITA', 'ESP', 'GRC', 'JPN', 'CHN'], regionTags: ['Monde', 'Europe', 'Amérique du Nord'],
    invariants: ['Stress du système bancaire international', 'Réponse publique par liquidité, garanties ou recapitalisation'],
    possibleManifestations: ['Krach bancaire', 'Crise immobilière', 'Récession mondiale graduelle', 'Crise souveraine différée'],
    playerVisibility: 'suspected', playerInfluence: 'medium',
  }),
  'eurozone-debt-crisis': anchor({
    id: 'eurozone-debt-crisis', title: 'Crise des dettes souveraines européennes',
    trendTitle: 'Tension entre discipline budgétaire et solidarité européenne',
    trendSummary: 'Les déséquilibres de compétitivité et les dettes publiques mettent à l’épreuve la crédibilité de la zone euro.',
    kind: 'economic', importance: 'major', trendId: 'eurozone-fragility', probableWindow: { start: '2010-01-01', end: '2013-12-31' },
    proposalThreshold: 54, activationThreshold: 78, basePressure: 55, historicalWeight: 94,
    affectedActors: ['GRC', 'ITA', 'ESP', 'DEU', 'FRA', 'PRT', 'IRL'], regionTags: ['Europe'],
    invariants: ['Pression des marchés sur plusieurs États', 'Conflit politique autour de l’austérité et des transferts'],
    possibleManifestations: ['Programme d’aide', 'Défaut restructuré', 'Sortie temporairement envisagée', 'Compromis budgétaire européen'],
    playerVisibility: 'known', playerInfluence: 'medium',
  }),
  'arab-spring': anchor({
    id: 'arab-spring', title: 'Printemps arabes',
    trendTitle: 'Pression sociale et politique sur les régimes arabes',
    trendSummary: 'Le chômage, la corruption et l’autoritarisme produisent une vague de contestation dont les issues divergent selon les pays.',
    kind: 'power_struggle', importance: 'major', probableWindow: { start: '2010-01-01', end: '2013-12-31' },
    proposalThreshold: 48, activationThreshold: 75, basePressure: 58, historicalWeight: 95,
    affectedActors: ['TUN', 'EGY', 'LBY', 'SYR', 'SAU', 'TUR', 'FRA', 'USA'], regionTags: ['Afrique du Nord', 'Moyen-Orient'],
    invariants: ['Mobilisations populaires transnationales', 'Arbitrage entre réforme, répression et transition'],
    possibleManifestations: ['Transition politique', 'Coup d’État', 'Répression de masse', 'Guerre civile'],
    playerVisibility: 'suspected', playerInfluence: 'medium',
  }),
  'fukushima-nuclear-shock': anchor({
    id: 'fukushima-nuclear-shock', title: 'Accident nucléaire de Fukushima',
    trendTitle: 'Réévaluation politique du risque nucléaire',
    trendSummary: 'Un accident nucléaire majeur force les gouvernements à arbitrer entre sécurité, souveraineté énergétique et coût de la transition.',
    kind: 'economic', importance: 'major', probableWindow: { start: '2011-01-01', end: '2012-12-31' },
    proposalThreshold: 55, activationThreshold: 80, basePressure: 45, historicalWeight: 78,
    affectedActors: ['JPN', 'DEU', 'FRA', 'USA', 'CHN'], regionTags: ['Asie de l’Est', 'Europe'],
    invariants: ['Réexamen des politiques nucléaires', 'Arbitrage entre sûreté et sécurité énergétique'],
    possibleManifestations: ['Fermeture de réacteurs', 'Maintien renforcé du nucléaire', 'Accélération des renouvelables'],
    playerVisibility: 'known', playerInfluence: 'high',
  }),
  'syrian-civil-war': anchor({
    id: 'syrian-civil-war', title: 'Guerre civile syrienne',
    trendTitle: 'Effondrement progressif de l’ordre régional au Levant',
    trendSummary: 'La contestation syrienne se transforme en conflit armé où interviennent progressivement puissances régionales et grandes puissances.',
    kind: 'conflict', importance: 'critical', trendId: 'arab-spring', probableWindow: { start: '2011-01-01', end: '2016-12-31' },
    proposalThreshold: 52, activationThreshold: 80, basePressure: 51, historicalWeight: 97,
    affectedActors: ['SYR', 'TUR', 'RUS', 'USA', 'FRA', 'IRN', 'SAU'], regionTags: ['Moyen-Orient'],
    invariants: ['Fragmentation de l’autorité syrienne', 'Intervention ou soutien extérieur'],
    possibleManifestations: ['Guerre civile longue', 'Partition de fait', 'Transition négociée', 'Intervention étrangère directe'],
    playerVisibility: 'suspected', playerInfluence: 'medium',
  }),
  'isis-territorial-expansion': anchor({
    id: 'isis-territorial-expansion', title: 'Expansion territoriale de l’État islamique',
    trendTitle: 'Transformation du djihadisme en proto-État territorial',
    trendSummary: 'L’effondrement de plusieurs autorités au Moyen-Orient permet à une organisation djihadiste de contrôler des territoires et des ressources.',
    kind: 'security', importance: 'critical', probableWindow: { start: '2013-01-01', end: '2017-12-31' },
    proposalThreshold: 56, activationThreshold: 82, basePressure: 47, historicalWeight: 93,
    affectedActors: ['IRQ', 'SYR', 'USA', 'FRA', 'GBR', 'TUR', 'IRN'], regionTags: ['Moyen-Orient'],
    invariants: ['Contrôle territorial temporaire', 'Coalition militaire ou renseignement contre l’organisation'],
    possibleManifestations: ['Expansion rapide', 'Insurrection clandestine', 'Endiguement précoce', 'Attentats extérieurs'],
    playerVisibility: 'suspected', playerInfluence: 'medium',
  }),
  'crimea-donbas': anchor({
    id: 'crimea-donbas', title: 'Annexion de la Crimée et guerre du Donbass',
    trendTitle: 'Rupture de l’ordre sécuritaire européen',
    trendSummary: 'La crise ukrainienne oppose le projet d’ancrage occidental de Kiev aux intérêts stratégiques russes dans l’espace postsoviétique.',
    kind: 'conflict', importance: 'critical', trendId: 'russia-revisionism', probableWindow: { start: '2013-01-01', end: '2016-12-31' },
    proposalThreshold: 55, activationThreshold: 82, basePressure: 49, historicalWeight: 98,
    affectedActors: ['UKR', 'RUS', 'USA', 'POL', 'DEU', 'FRA', 'GBR'], regionTags: ['Europe', 'Eurasie'],
    invariants: ['Contestations territoriales en Ukraine', 'Réponse occidentale par sanctions et soutien politique'],
    possibleManifestations: ['Annexion rapide', 'Conflit gelé', 'Accord de neutralité', 'Guerre ouverte prolongée'],
    playerVisibility: 'suspected', playerInfluence: 'medium',
  }),
  'belt-and-road': anchor({
    id: 'belt-and-road', title: 'Lancement des Nouvelles routes de la soie',
    trendTitle: 'Projection économique et logistique chinoise',
    trendSummary: 'Pékin utilise les infrastructures, les ports, le crédit et le commerce pour accroître son influence au-delà de l’Asie orientale.',
    kind: 'cooperation', importance: 'major', probableWindow: { start: '2013-01-01', end: '2018-12-31' },
    proposalThreshold: 46, activationThreshold: 73, basePressure: 44, historicalWeight: 88,
    affectedActors: ['CHN', 'IND', 'PAK', 'AUS', 'FRA', 'DEU', 'USA'], regionTags: ['Asie', 'Europe', 'Afrique'],
    invariants: ['Financement d’infrastructures par la Chine', 'Débat sur dépendance et souveraineté'],
    possibleManifestations: ['Accord portuaire', 'Projet ferroviaire', 'Crise de dette partenaire', 'Contre-offre occidentale'],
    playerVisibility: 'known', playerInfluence: 'medium',
  }),
  'paris-climate-agreement': anchor({
    id: 'paris-climate-agreement', title: 'Accord de Paris sur le climat',
    trendTitle: 'Institutionnalisation de la transition climatique',
    trendSummary: 'Les États cherchent un compromis mondial entre réduction des émissions, développement industriel et financement des pays vulnérables.',
    kind: 'cooperation', importance: 'major', probableWindow: { start: '2015-01-01', end: '2016-12-31' },
    proposalThreshold: 44, activationThreshold: 70, basePressure: 49, historicalWeight: 89,
    affectedActors: ['FRA', 'DEU', 'USA', 'CHN', 'IND', 'BRA', 'AUS'], regionTags: ['Monde', 'Europe', 'Asie'],
    invariants: ['Objectif climatique multilatéral', 'Tension entre ambition et contraintes industrielles'],
    possibleManifestations: ['Accord global', 'Engagement minimal', 'Retrait temporaire d’une puissance', 'Coalition climatique régionale'],
    playerVisibility: 'known', playerInfluence: 'medium',
  }),
  'european-migration-crisis': anchor({
    id: 'european-migration-crisis', title: 'Crise migratoire européenne',
    trendTitle: 'Pression migratoire et fracture politique européenne',
    trendSummary: 'Les guerres et crises régionales provoquent des arrivées importantes en Europe et opposent solidarité, contrôle des frontières et souveraineté nationale.',
    kind: 'diplomatic_crisis', importance: 'major', probableWindow: { start: '2015-01-01', end: '2017-12-31' },
    proposalThreshold: 50, activationThreshold: 76, basePressure: 48, historicalWeight: 87,
    affectedActors: ['DEU', 'FRA', 'ITA', 'GRC', 'TUR', 'SYR', 'HUN', 'GBR'], regionTags: ['Europe', 'Moyen-Orient'],
    invariants: ['Arrivées et déplacements forcés', 'Désaccord entre gouvernements européens'],
    possibleManifestations: ['Accord de répartition', 'Fermeture de frontières', 'Accord avec la Turquie', 'Montée des partis anti-immigration'],
    playerVisibility: 'known', playerInfluence: 'medium',
  }),
  'brexit': anchor({
    id: 'brexit', title: 'Brexit',
    trendTitle: 'Désintégration partielle du projet européen',
    trendSummary: 'Le Royaume-Uni remet en cause l’intégration européenne, ouvrant une longue négociation commerciale et institutionnelle.',
    kind: 'diplomatic_crisis', importance: 'major', probableWindow: { start: '2016-01-01', end: '2020-12-31' },
    proposalThreshold: 48, activationThreshold: 74, basePressure: 42, historicalWeight: 93,
    affectedActors: ['GBR', 'FRA', 'DEU', 'ITA', 'ESP', 'IRL'], regionTags: ['Europe'],
    invariants: ['Négociation du statut britannique', 'Réorganisation des relations commerciales et de sécurité'],
    possibleManifestations: ['Sortie négociée', 'Report du départ', 'Accord minimal', 'Crise constitutionnelle britannique'],
    playerVisibility: 'known', playerInfluence: 'high',
  }),
  'populist-turn': anchor({
    id: 'populist-turn', title: 'Tournant populiste et nationaliste occidental',
    trendTitle: 'Polarisation des démocraties occidentales',
    trendSummary: 'La défiance envers les institutions, les inégalités et les crises migratoires renforcent les forces politiques anti-système.',
    kind: 'power_struggle', importance: 'major', probableWindow: { start: '2016-01-01', end: '2020-12-31' },
    proposalThreshold: 46, activationThreshold: 72, basePressure: 45, historicalWeight: 86,
    affectedActors: ['USA', 'GBR', 'FRA', 'ITA', 'DEU', 'POL'], regionTags: ['Europe', 'Amérique du Nord'],
    invariants: ['Polarisation politique accrue', 'Pression sur les médias, administrations et alliances'],
    possibleManifestations: ['Victoire électorale populiste', 'Coalition de rupture', 'Blocage parlementaire', 'Recentrage institutionnel'],
    playerVisibility: 'known', playerInfluence: 'high',
  }),
  'us-china-trade-war': anchor({
    id: 'us-china-trade-war', title: 'Guerre commerciale et technologique États-Unis–Chine',
    trendTitle: 'Découplage technologique et commercial sino-américain',
    trendSummary: 'Washington et Pékin commencent à traiter leurs dépendances industrielles et technologiques comme des risques de sécurité nationale.',
    kind: 'diplomatic_crisis', importance: 'major', probableWindow: { start: '2018-01-01', end: '2020-12-31' },
    proposalThreshold: 52, activationThreshold: 76, basePressure: 49, historicalWeight: 94,
    affectedActors: ['USA', 'CHN', 'JPN', 'KOR', 'DEU', 'FRA', 'IND'], regionTags: ['Asie de l’Est', 'Amérique du Nord', 'Europe'],
    invariants: ['Restrictions technologiques et commerciales', 'Réorganisation des chaînes de valeur'],
    possibleManifestations: ['Droits de douane', 'Blocus technologique ciblé', 'Accord temporaire', 'Course aux semi-conducteurs'],
    playerVisibility: 'known', playerInfluence: 'medium',
  }),
  'hong-kong-crisis': anchor({
    id: 'hong-kong-crisis', title: 'Crise de Hong Kong',
    trendTitle: 'Durcissement de la souveraineté chinoise',
    trendSummary: 'La contestation hongkongaise met à l’épreuve le principe « un pays, deux systèmes » et les relations entre Pékin et les démocraties occidentales.',
    kind: 'power_struggle', importance: 'major', probableWindow: { start: '2019-01-01', end: '2020-12-31' },
    proposalThreshold: 54, activationThreshold: 78, basePressure: 47, historicalWeight: 83,
    affectedActors: ['CHN', 'GBR', 'USA', 'FRA', 'DEU', 'AUS'], regionTags: ['Asie de l’Est'],
    invariants: ['Confrontation entre autonomie locale et souveraineté de Pékin', 'Réaction diplomatique occidentale'],
    possibleManifestations: ['Loi de sécurité', 'Répression graduée', 'Compromis institutionnel', 'Sanctions ciblées'],
    playerVisibility: 'known', playerInfluence: 'low',
  }),
  'iran-nuclear-tension': anchor({
    id: 'iran-nuclear-tension', title: 'Crise de l’accord nucléaire iranien',
    trendTitle: 'Désintégration progressive du compromis nucléaire iranien',
    trendSummary: 'Le retrait américain et le retour des sanctions poussent l’Iran, l’Europe et les puissances régionales à recalculer le risque de prolifération.',
    kind: 'diplomatic_crisis', importance: 'major', probableWindow: { start: '2018-01-01', end: '2020-12-31' },
    proposalThreshold: 50, activationThreshold: 77, basePressure: 44, historicalWeight: 88,
    affectedActors: ['IRN', 'USA', 'FRA', 'GBR', 'DEU', 'ISR', 'SAU'], regionTags: ['Moyen-Orient', 'Europe'],
    invariants: ['Sanctions américaines', 'Arbitrage européen entre commerce et non-prolifération'],
    possibleManifestations: ['Reprise des sanctions', 'Accord intérimaire', 'Escalade militaire limitée', 'Maintien d’un compromis fragile'],
    playerVisibility: 'known', playerInfluence: 'medium',
  }),
  'covid-pandemic': anchor({
    id: 'covid-pandemic', title: 'Pandémie mondiale de Covid-19',
    trendTitle: 'Crise sanitaire mondiale et sortie de pandémie',
    trendSummary: 'Une crise sanitaire mondiale bouleverse la mobilité, la production, les finances publiques, les chaînes logistiques et la confiance politique.',
    kind: 'economic', importance: 'critical', probableWindow: { start: '2020-01-01', end: '2023-12-31' },
    proposalThreshold: 40, activationThreshold: 72, basePressure: 38, historicalWeight: 100,
    affectedActors: ['CHN', 'USA', 'FRA', 'DEU', 'ITA', 'GBR', 'IND', 'BRA', 'JPN'], regionTags: ['Monde'],
    invariants: ['Propagation internationale d’une maladie émergente', 'Réponse sanitaire et économique exceptionnelle'],
    possibleManifestations: ['Confinements généralisés', 'Restrictions ciblées', 'Crise sanitaire prolongée', 'Sortie rapide grâce à la vaccination'],
    playerVisibility: 'suspected', playerInfluence: 'medium',
  }),
};

export function createHistoricalAnchors2000() {
  return structuredClone(historicalAnchors2000);
}
