import type { CapacityState, CountryState } from './types';

/**
 * Compact national fiches for the first global prototype.
 * Values are rounded scenario inputs for 1 January 2000, not an encyclopaedia
 * and not a claim of statistical precision. Regional detail belongs in a
 * separate TerritoryDataset and is only added when gameplay needs it.
 */
export type NationalBaselineDescriptor = {
  id: string; name: string; flag: string; leader: string; regime: string; government: string;
  orientation: 'liberal' | 'social' | 'nationalist' | 'party_state' | 'military' | 'monarchy' | 'theocratic' | 'fragile' | 'transition';
  scale: number; gdp: number; population: number; growth: number; populationGrowth: number;
  inflation: number; unemployment: number; industry: number; openness: number; confidence: number;
  stability: number; security: number; interests: string[]; vulnerabilities: string[];
  redLines: string[]; partners: string[]; rivals: string[];
};

const d = (input: NationalBaselineDescriptor) => input;

/** 80 additional countries, selected for geopolitical, economic or regional relevance. */
export const nationalBaseline2000: NationalBaselineDescriptor[] = [
  d({ id:'AFG', name:'Afghanistan', flag:'🇦🇫', leader:'Mohammed Omar', regime:'Émirat islamique de facto', government:'Direction talibane', orientation:'theocratic', scale:18, gdp:4.1, population:20.8, growth:3.2, populationGrowth:1.2, inflation:5, unemployment:35, industry:12, openness:22, confidence:28, stability:18, security:22, interests:['Préserver le contrôle territorial et religieux'], vulnerabilities:['Guerre civile','Économie de subsistance','Isolement diplomatique'], redLines:['Présence militaire étrangère'], partners:['PAK'], rivals:['IRN'] }),
  d({ id:'AGO', name:'Angola', flag:'🇦🇴', leader:'José Eduardo dos Santos', regime:'République présidentielle autoritaire', government:'MPLA au pouvoir', orientation:'party_state', scale:32, gdp:9.1, population:13.9, growth:3.0, populationGrowth:3.1, inflation:300, unemployment:28, industry:36, openness:62, confidence:42, stability:35, security:32, interests:['Conserver le pouvoir','Monétiser les hydrocarbures'], vulnerabilities:['Guerre civile','Dépendance pétrolière','Pauvreté'], redLines:['Perte du contrôle des régions pétrolières'], partners:['PRT'], rivals:[] }),
  d({ id:'ARE', name:'Émirats arabes unis', flag:'🇦🇪', leader:'Zayed ben Sultan Al Nahyane', regime:'Fédération de monarchies', government:'Conseil suprême des émirs', orientation:'monarchy', scale:46, gdp:104, population:3.0, growth:10.0, populationGrowth:6.0, inflation:2.0, unemployment:3, industry:42, openness:88, confidence:66, stability:78, security:72, interests:['Diversifier les revenus pétroliers','Devenir une plateforme commerciale'], vulnerabilities:['Dépendance aux hydrocarbures','Main-d’œuvre étrangère','Vulnérabilité régionale'], redLines:['Menace sur les monarchies du Golfe'], partners:['SAU','USA','GBR'], rivals:['IRN'] }),
  d({ id:'ARG', name:'Argentine', flag:'🇦🇷', leader:'Fernando de la Rúa', regime:'République fédérale présidentielle', government:'Coalition de l’Alliance', orientation:'liberal', scale:52, gdp:284, population:36.9, growth:-0.8, populationGrowth:1.0, inflation:-0.9, unemployment:15, industry:25, openness:54, confidence:76, stability:51, security:55, interests:['Préserver la convertibilité','Restaurer la confiance financière'], vulnerabilities:['Dette extérieure','Récession','Fragilité bancaire'], redLines:['Abandon désordonné de la monnaie'], partners:['BRA','USA','ESP'], rivals:[] }),
  d({ id:'AUT', name:'Autriche', flag:'🇦🇹', leader:'Viktor Klima', regime:'République parlementaire', government:'Grande coalition SPÖ–ÖVP (au 1er janvier 2000)', orientation:'nationalist', scale:42, gdp:196, population:8.0, growth:3.4, populationGrowth:0.3, inflation:2.0, unemployment:3.8, industry:28, openness:76, confidence:88, stability:68, security:62, interests:['Ancrage européen','Prospérité alpine'], vulnerabilities:['Dépendance au marché allemand','Tensions de coalition'], redLines:['Marginalisation dans l’Union européenne'], partners:['DEU','ITA','CHE'], rivals:[] }),
  d({ id:'BEL', name:'Belgique', flag:'🇧🇪', leader:'Guy Verhofstadt', regime:'Monarchie parlementaire fédérale', government:'Coalition arc-en-ciel', orientation:'liberal', scale:45, gdp:236, population:10.2, growth:3.7, populationGrowth:0.2, inflation:2.5, unemployment:8.5, industry:24, openness:92, confidence:91, stability:65, security:60, interests:['Approfondir l’intégration européenne','Maintenir la cohésion fédérale'], vulnerabilities:['Cloivage communautaire','Dépendance commerciale'], redLines:['Rupture institutionnelle belge'], partners:['FRA','DEU','NLD'], rivals:[] }),
  d({ id:'BGD', name:'Bangladesh', flag:'🇧🇩', leader:'Sheikh Hasina', regime:'République parlementaire instable', government:'Ligue Awami', orientation:'transition', scale:28, gdp:53, population:128.7, growth:5.3, populationGrowth:1.9, inflation:2.2, unemployment:3, industry:18, openness:48, confidence:52, stability:39, security:45, interests:['Industrialiser le textile','Réduire la pauvreté'], vulnerabilities:['Catastrophes climatiques','Densité démographique','Polarisation politique'], redLines:['Coup d’État militaire'], partners:['IND','CHN'], rivals:[] }),
  d({ id:'BHR', name:'Bahreïn', flag:'🇧🇭', leader:'Hamad ben Issa Al Khalifa', regime:'Monarchie constitutionnelle contrôlée', government:'Maison Al Khalifa', orientation:'monarchy', scale:27, gdp:9, population:0.65, growth:5.0, populationGrowth:2.4, inflation:-0.7, unemployment:4, industry:48, openness:82, confidence:58, stability:54, security:58, interests:['Préserver la monarchie','Développer les services financiers'], vulnerabilities:['Ressources pétrolières limitées','Clivage confessionnel','Dépendance saoudienne'], redLines:['Soulèvement contre la dynastie'], partners:['SAU','USA'], rivals:['IRN'] }),
  d({ id:'BLR', name:'Biélorussie', flag:'🇧🇾', leader:'Alexandre Loukachenko', regime:'République présidentielle autoritaire', government:'Présidence centralisée', orientation:'party_state', scale:30, gdp:12, population:10.0, growth:3.5, populationGrowth:-0.3, inflation:168, unemployment:2, industry:42, openness:44, confidence:48, stability:52, security:62, interests:['Maintenir l’économie administrée','Préserver l’orbite russe'], vulnerabilities:['Dépendance énergétique à la Russie','Isolement financier','Vieillissement'], redLines:['Perte de souveraineté face à Moscou'], partners:['RUS'], rivals:[] }),
  d({ id:'BGR', name:'Bulgarie', flag:'🇧🇬', leader:'Ivan Kostov', regime:'République parlementaire', government:'Union des forces démocratiques', orientation:'transition', scale:34, gdp:13, population:8.1, growth:5.0, populationGrowth:-0.8, inflation:10.3, unemployment:16, industry:27, openness:62, confidence:65, stability:49, security:51, interests:['Préparer l’adhésion européenne','Stabiliser la monnaie'], vulnerabilities:['Transition sociale','Émigration','Corruption'], redLines:['Retour à la tutelle russe'], partners:['DEU','GRC','USA'], rivals:[] }),
  d({ id:'BIH', name:'Bosnie-Herzégovine', flag:'🇧🇦', leader:'Présidence collégiale', regime:'République fédérale sous tutelle internationale', government:'Institutions de Dayton', orientation:'transition', scale:22, gdp:5, population:3.7, growth:5.5, populationGrowth:0.7, inflation:4, unemployment:40, industry:16, openness:48, confidence:46, stability:33, security:44, interests:['Consolider la paix','Reconstruire l’économie'], vulnerabilities:['Institutions fragmentées','Chômage','Tensions communautaires'], redLines:['Réouverture du conflit'], partners:['DEU','FRA'], rivals:[] }),
  d({ id:'BOL', name:'Bolivie', flag:'🇧🇴', leader:'Hugo Banzer', regime:'République présidentielle', government:'Coalition parlementaire conservatrice', orientation:'nationalist', scale:25, gdp:8, population:8.3, growth:2.5, populationGrowth:2.3, inflation:4.6, unemployment:8, industry:18, openness:46, confidence:60, stability:48, security:49, interests:['Développer les hydrocarbures','Maintenir l’accès maritime régional'], vulnerabilities:['Pauvreté','Instabilité sociale','Dépendance aux matières premières'], redLines:['Perte de contrôle sur les ressources'], partners:['BRA','ARG'], rivals:[] }),
  d({ id:'CHE', name:'Suisse', flag:'🇨🇭', leader:'Adolf Ogi', regime:'Confédération fédérale collégiale', government:'Conseil fédéral', orientation:'liberal', scale:49, gdp:271, population:7.2, growth:3.6, populationGrowth:0.5, inflation:1.6, unemployment:2.7, industry:32, openness:88, confidence:95, stability:84, security:66, interests:['Préserver la neutralité armée','Protéger la place financière'], vulnerabilities:['Exposition financière','Pression européenne','Franc fort'], redLines:['Abandon forcé de la neutralité'], partners:['DEU','FRA','ITA'], rivals:[] }),
  d({ id:'CHL', name:'Chili', flag:'🇨🇱', leader:'Ricardo Lagos', regime:'République présidentielle', government:'Concertación démocratique', orientation:'liberal', scale:39, gdp:75, population:15.4, growth:4.5, populationGrowth:1.3, inflation:3.8, unemployment:9.2, industry:22, openness:72, confidence:78, stability:67, security:56, interests:['Consolider la démocratie','Développer les exportations minières'], vulnerabilities:['Dépendance au cuivre','Inégalités','Litiges territoriaux'], redLines:['Retour à l’autoritarisme'], partners:['USA','ARG','PER'], rivals:[] }),
  d({ id:'COL', name:'Colombie', flag:'🇨🇴', leader:'Andrés Pastrana', regime:'République présidentielle', government:'Administration Pastrana', orientation:'liberal', scale:39, gdp:99, population:39.0, growth:2.9, populationGrowth:1.8, inflation:9.2, unemployment:16, industry:24, openness:45, confidence:68, stability:35, security:24, interests:['Restaurer le contrôle territorial','Attirer l’aide et l’investissement'], vulnerabilities:['Conflit armé','Narco-économie','Déplacement de population'], redLines:['Extension des guérillas aux centres urbains'], partners:['USA','ESP'], rivals:[] }),
  d({ id:'COD', name:'République démocratique du Congo', flag:'🇨🇩', leader:'Laurent-Désiré Kabila', regime:'République présidentielle en guerre', government:'Alliance des forces démocratiques', orientation:'military', scale:34, gdp:19, population:51.6, growth:-6.9, populationGrowth:3.1, inflation:550, unemployment:30, industry:12, openness:35, confidence:24, stability:18, security:14, interests:['Préserver l’intégrité territoriale','Contrôler les ressources minières'], vulnerabilities:['Guerre régionale','État fragmenté','Pauvreté extrême'], redLines:['Partition du territoire'], partners:['AGO','ZWE'], rivals:['RWA','UGA'] }),
  d({ id:'CRI', name:'Costa Rica', flag:'🇨🇷', leader:'Miguel Ángel Rodríguez', regime:'République présidentielle démocratique', government:'Parti Unité sociale-chrétienne', orientation:'liberal', scale:27, gdp:16, population:3.9, growth:3.8, populationGrowth:2.2, inflation:11.2, unemployment:5.2, industry:24, openness:58, confidence:78, stability:72, security:62, interests:['Préserver la démocratie','Attirer les technologies'], vulnerabilities:['Petite économie','Vulnérabilité externe','Inégalités'], redLines:['Remilitarisation politique'], partners:['USA','PAN'], rivals:[] }),
  d({ id:'CUB', name:'Cuba', flag:'🇨🇺', leader:'Fidel Castro', regime:'République socialiste à parti unique', government:'Parti communiste cubain', orientation:'party_state', scale:35, gdp:30, population:11.1, growth:5.6, populationGrowth:0.4, inflation:3, unemployment:6, industry:30, openness:28, confidence:39, stability:59, security:72, interests:['Préserver le régime','Desserrer l’embargo'], vulnerabilities:['Isolement économique','Dépendance au tourisme','Vieillissement'], redLines:['Changement de régime imposé'], partners:['VEN'], rivals:['USA'] }),
  d({ id:'CZE', name:'République tchèque', flag:'🇨🇿', leader:'Václav Havel', regime:'République parlementaire', government:'Coalition autour de la social-démocratie', orientation:'transition', scale:39, gdp:62, population:10.3, growth:3.6, populationGrowth:-0.1, inflation:3.9, unemployment:8.8, industry:35, openness:78, confidence:79, stability:63, security:57, interests:['Préparer l’intégration européenne','Moderniser l’industrie'], vulnerabilities:['Dépendance allemande','Restructuration bancaire','Vieillissement'], redLines:['Retour dans la sphère russe'], partners:['DEU','POL','AUT'], rivals:[] }),
  d({ id:'DNK', name:'Danemark', flag:'🇩🇰', leader:'Poul Nyrup Rasmussen', regime:'Monarchie parlementaire', government:'Coalition sociale-démocrate', orientation:'social', scale:43, gdp:164, population:5.3, growth:2.9, populationGrowth:0.3, inflation:2.7, unemployment:4.9, industry:25, openness:82, confidence:93, stability:78, security:68, interests:['Préserver l’État social','Peser en Baltique'], vulnerabilities:['Petite économie ouverte','Réserves envers l’euro'], redLines:['Démantèlement brutal de l’État social'], partners:['DEU','GBR','NOR'], rivals:[] }),
  d({ id:'DOM', name:'République dominicaine', flag:'🇩🇴', leader:'Hipólito Mejía', regime:'République présidentielle', government:'Parti révolutionnaire dominicain', orientation:'liberal', scale:28, gdp:23, population:8.6, growth:4.7, populationGrowth:1.7, inflation:7.7, unemployment:13, industry:18, openness:54, confidence:61, stability:52, security:50, interests:['Développer le tourisme et les zones franches'], vulnerabilities:['Dépendance aux transferts','Infrastructures','Catastrophes naturelles'], redLines:['Crise institutionnelle majeure'], partners:['USA'], rivals:[] }),
  d({ id:'ECU', name:'Équateur', flag:'🇪🇨', leader:'Gustavo Noboa', regime:'République présidentielle en dollarisation', government:'Coalition de transition', orientation:'transition', scale:29, gdp:18, population:12.6, growth:0.8, populationGrowth:1.9, inflation:96, unemployment:10, industry:19, openness:48, confidence:56, stability:37, security:47, interests:['Stabiliser la dollarisation','Relancer la production pétrolière'], vulnerabilities:['Crise bancaire','Pauvreté','Instabilité politique'], redLines:['Retour à l’hyperinflation'], partners:['USA','COL'], rivals:[] }),
  d({ id:'EGY', name:'Égypte', flag:'🇪🇬', leader:'Hosni Moubarak', regime:'République présidentielle autoritaire', government:'Parti national démocratique', orientation:'military', scale:58, gdp:99, population:68.6, growth:5.7, populationGrowth:1.9, inflation:3.8, unemployment:9, industry:25, openness:45, confidence:64, stability:55, security:61, interests:['Préserver le rôle régional','Sécuriser le Nil et le canal de Suez'], vulnerabilities:['Pression démographique','Chômage des jeunes','Dépendance alimentaire'], redLines:['Menace sur le régime ou le Nil'], partners:['USA','SAU'], rivals:['ISR'] }),
  d({ id:'EST', name:'Estonie', flag:'🇪🇪', leader:'Lennart Meri', regime:'République parlementaire', government:'Coalition de centre droit', orientation:'liberal', scale:25, gdp:5.7, population:1.4, growth:6.0, populationGrowth:0.5, inflation:4, unemployment:13, industry:22, openness:78, confidence:76, stability:61, security:48, interests:['Adhérer à l’UE et à l’OTAN','Réduire la dépendance russe'], vulnerabilities:['Petite taille','Minorité russophone','Dépendance énergétique'], redLines:['Pression russe sur la souveraineté'], partners:['POL','USA','FIN'], rivals:['RUS'] }),
  d({ id:'ETH', name:'Éthiopie', flag:'🇪🇹', leader:'Meles Zenawi', regime:'République fédérale à parti dominant', government:'Front démocratique révolutionnaire', orientation:'party_state', scale:34, gdp:8, population:63.5, growth:5.5, populationGrowth:2.4, inflation:0.7, unemployment:20, industry:12, openness:28, confidence:38, stability:34, security:37, interests:['Préserver l’unité fédérale','Développer l’agriculture'], vulnerabilities:['Pauvreté','Conflits périphériques','Dépendance climatique'], redLines:['Sécession territoriale'], partners:['USA','KEN'], rivals:['ERI'] }),
  d({ id:'FIN', name:'Finlande', flag:'🇫🇮', leader:'Paavo Lipponen', regime:'République parlementaire', government:'Coalition sociale-démocrate (présidence Ahtisaari au 1er janvier)', orientation:'social', scale:42, gdp:126, population:5.2, growth:5.1, populationGrowth:0.3, inflation:3, unemployment:9.8, industry:34, openness:84, confidence:94, stability:77, security:66, interests:['Préserver la neutralité active','Développer les télécoms'], vulnerabilities:['Dépendance commerciale','Frontière russe','Chômage structurel'], redLines:['Violation du territoire national'], partners:['SWE','DEU','USA'], rivals:['RUS'] }),
  d({ id:'GHA', name:'Ghana', flag:'🇬🇭', leader:'Jerry Rawlings', regime:'République présidentielle', government:'Congrès démocratique national', orientation:'social', scale:27, gdp:5, population:19.3, growth:3.7, populationGrowth:2.2, inflation:25, unemployment:12, industry:18, openness:43, confidence:55, stability:55, security:48, interests:['Consolider la démocratie','Diversifier cacao et or'], vulnerabilities:['Dette','Dépendance aux matières premières','Pauvreté rurale'], redLines:['Retour au régime militaire'], partners:['USA','NGA'], rivals:[] }),
  d({ id:'GRC', name:'Grèce', flag:'🇬🇷', leader:'Costas Simitis', regime:'République parlementaire', government:'PASOK modernisateur', orientation:'social', scale:42, gdp:132, population:10.9, growth:4.5, populationGrowth:0.3, inflation:2.9, unemployment:11, industry:20, openness:66, confidence:82, stability:62, security:60, interests:['Entrer dans l’euro','Affirmer la position égéenne'], vulnerabilities:['Dette publique','Dépendance énergétique','Tensions avec la Turquie'], redLines:['Concession territoriale en mer Égée'], partners:['FRA','ITA','CYP'], rivals:['TUR'] }),
  d({ id:'GTM', name:'Guatemala', flag:'🇬🇹', leader:'Alfonso Portillo', regime:'République présidentielle', government:'Front républicain guatémaltèque', orientation:'nationalist', scale:26, gdp:19, population:11.4, growth:3.8, populationGrowth:2.7, inflation:6, unemployment:4, industry:18, openness:45, confidence:48, stability:41, security:35, interests:['Stabiliser l’après-guerre civile','Développer les exportations'], vulnerabilities:['Inégalités','Criminalité','Institutions faibles'], redLines:['Retour à la guerre civile'], partners:['USA','MEX'], rivals:[] }),
  d({ id:'HRV', name:'Croatie', flag:'🇭🇷', leader:'Stjepan Mesić', regime:'République parlementaire', government:'Coalition réformatrice', orientation:'transition', scale:31, gdp:21, population:4.4, growth:3.8, populationGrowth:-0.3, inflation:4.5, unemployment:17, industry:25, openness:66, confidence:66, stability:52, security:49, interests:['Normaliser les relations européennes','Reconstruire le littoral et l’industrie'], vulnerabilities:['Chômage','Héritage de guerre','Dette externe'], redLines:['Révision forcée des frontières'], partners:['DEU','ITA'], rivals:[] }),
  d({ id:'HUN', name:'Hongrie', flag:'🇭🇺', leader:'Viktor Orbán', regime:'République parlementaire', government:'Coalition Fidesz–petits propriétaires', orientation:'nationalist', scale:35, gdp:48, population:10.2, growth:4.4, populationGrowth:-0.3, inflation:9.8, unemployment:6.4, industry:28, openness:76, confidence:72, stability:58, security:52, interests:['Adhérer à l’Union européenne','Attirer l’industrie allemande'], vulnerabilities:['Déclin démographique','Dépendance au capital étranger','Question des minorités'], redLines:['Perte de souveraineté nationale'], partners:['DEU','AUT','POL'], rivals:[] }),
  d({ id:'IDN', name:'Indonésie', flag:'🇮🇩', leader:'Abdurrahman Wahid', regime:'République présidentielle en démocratisation', government:'Coalition pluraliste', orientation:'transition', scale:60, gdp:165, population:211.5, growth:4.9, populationGrowth:1.5, inflation:3.7, unemployment:6.1, industry:29, openness:52, confidence:61, stability:43, security:42, interests:['Consolider la transition démocratique','Préserver l’unité archipélagique'], vulnerabilities:['Crise bancaire','Séparatismes','Pauvreté'], redLines:['Démembrement de l’archipel'], partners:['JPN','AUS','SGP'], rivals:[] }),
  d({ id:'IRL', name:'Irlande', flag:'🇮🇪', leader:'Bertie Ahern', regime:'République parlementaire', government:'Fianna Fáil et démocrates progressistes', orientation:'liberal', scale:39, gdp:100, population:3.8, growth:9.4, populationGrowth:1.0, inflation:5.6, unemployment:4.3, industry:30, openness:100, confidence:88, stability:76, security:55, interests:['Poursuivre le rattrapage économique','Consolider la paix en Ulster'], vulnerabilities:['Dépendance aux multinationales','Surchauffe immobilière','Petite économie'], redLines:['Retour de la violence en Irlande du Nord'], partners:['GBR','USA','DEU'], rivals:[] }),
  d({ id:'IRN', name:'Iran', flag:'🇮🇷', leader:'Mohammad Khatami', regime:'République islamique à pouvoir dual', government:'Réformateurs sous tutelle religieuse', orientation:'theocratic', scale:55, gdp:109.6, population:63.7, growth:5.8, populationGrowth:1.4, inflation:14.5, unemployment:14, industry:29, openness:34, confidence:54, stability:49, security:64, interests:['Préserver l’autonomie stratégique','Accroître l’influence régionale'], vulnerabilities:['Sanctions','Dépendance pétrolière','Conflit entre réformateurs et conservateurs'], redLines:['Encerclement militaire américain'], partners:['RUS','SYR'], rivals:['USA','ISR','SAU'] }),
  d({ id:'IRQ', name:'Irak', flag:'🇮🇶', leader:'Saddam Hussein', regime:'République baasiste autoritaire sous sanctions', government:'Parti Baas', orientation:'military', scale:44, gdp:48.4, population:23.1, growth:16.8, populationGrowth:2.8, inflation:5.0, unemployment:15, industry:30, openness:20, confidence:26, stability:31, security:40, interests:['Desserrer les sanctions','Préserver l’intégrité du régime'], vulnerabilities:['Sanctions internationales','Infrastructures dégradées','Minorités et frontières'], redLines:['Renversement du régime'], partners:['SYR','JOR'], rivals:['USA','KWT'] }),
  d({ id:'ISL', name:'Islande', flag:'🇮🇸', leader:'Davíð Oddsson', regime:'République parlementaire', government:'Parti de l’indépendance', orientation:'liberal', scale:25, gdp:8, population:0.28, growth:4.8, populationGrowth:0.8, inflation:5, unemployment:2.3, industry:24, openness:78, confidence:90, stability:82, security:50, interests:['Préserver la souveraineté maritime','Développer la pêche et la finance'], vulnerabilities:['Petite économie','Dépendance à la pêche','Isolement géographique'], redLines:['Perte des zones de pêche'], partners:['USA','NOR','GBR'], rivals:[] }),
  d({ id:'ISR', name:'Israël', flag:'🇮🇱', leader:'Ehud Barak', regime:'Démocratie parlementaire', government:'Coalition travailliste', orientation:'nationalist', scale:50, gdp:132, population:6.3, growth:8.7, populationGrowth:2.5, inflation:1.1, unemployment:8.8, industry:31, openness:74, confidence:78, stability:47, security:82, interests:['Préserver la sécurité nationale','Maintenir la supériorité technologique'], vulnerabilities:['Conflit israélo-palestinien','Dépendance américaine','Polarisation religieuse'], redLines:['Attaque contre le territoire national','Menace existentielle'], partners:['USA','DEU'], rivals:['SYR','IRN','EGY'] }),
  d({ id:'JOR', name:'Jordanie', flag:'🇯🇴', leader:'Abdallah II', regime:'Monarchie constitutionnelle dirigée', government:'Maison hachémite', orientation:'monarchy', scale:32, gdp:8.5, population:5.0, growth:4.1, populationGrowth:2.8, inflation:0.7, unemployment:13, industry:18, openness:56, confidence:58, stability:58, security:61, interests:['Préserver la monarchie','Maintenir l’aide extérieure'], vulnerabilities:['Rareté de l’eau','Réfugiés','Dépendance énergétique'], redLines:['Déstabilisation de la monarchie'], partners:['USA','SAU','GBR'], rivals:['IRQ'] }),
  d({ id:'KAZ', name:'Kazakhstan', flag:'🇰🇿', leader:'Noursoultan Nazarbaïev', regime:'République présidentielle autoritaire', government:'Présidence et élites énergétiques', orientation:'nationalist', scale:37, gdp:18, population:14.9, growth:9.8, populationGrowth:0.3, inflation:13.2, unemployment:12, industry:35, openness:54, confidence:45, stability:52, security:58, interests:['Monétiser les hydrocarbures','Préserver l’équilibre entre Russie et Occident'], vulnerabilities:['Enclavement','Dépendance aux matières premières','Tensions ethniques'], redLines:['Perte de souveraineté énergétique'], partners:['RUS','CHN','USA'], rivals:[] }),
  d({ id:'KEN', name:'Kenya', flag:'🇰🇪', leader:'Daniel arap Moi', regime:'République présidentielle autoritaire', government:'KANU', orientation:'nationalist', scale:32, gdp:13, population:30.3, growth:0.5, populationGrowth:2.7, inflation:11.9, unemployment:14, industry:17, openness:42, confidence:48, stability:43, security:42, interests:['Préserver la stabilité intérieure','Développer le rôle régional'], vulnerabilities:['Pauvreté','Corruption','Sécheresses'], redLines:['Violence intercommunautaire généralisée'], partners:['UGA','GBR','USA'], rivals:[] }),
  d({ id:'KOR', name:'Corée du Sud', flag:'🇰🇷', leader:'Kim Dae-jung', regime:'République présidentielle démocratique', government:'Coalition réformatrice', orientation:'liberal', scale:66, gdp:562, population:47.0, growth:9.1, populationGrowth:0.8, inflation:2.3, unemployment:4.4, industry:41, openness:72, confidence:84, stability:61, security:79, interests:['Réduire la dépendance sécuritaire','Préparer la réunification sans choc'], vulnerabilities:['Menace nord-coréenne','Dépendance aux exportations','Conglomérats endettés'], redLines:['Attaque nord-coréenne','Effondrement désordonné du Nord'], partners:['USA','JPN'], rivals:['PRK'] }),
  d({ id:'KWT', name:'Koweït', flag:'🇰🇼', leader:'Jaber Al-Ahmad Al-Sabah', regime:'Monarchie constitutionnelle du Golfe', government:'Maison Al Sabah et Assemblée', orientation:'monarchy', scale:37, gdp:37, population:2.0, growth:6.0, populationGrowth:3.2, inflation:1.6, unemployment:1.5, industry:39, openness:63, confidence:55, stability:56, security:74, interests:['Garantir la sécurité du territoire','Préserver les revenus pétroliers'], vulnerabilities:['Dépendance pétrolière','Vulnérabilité irakienne','Main-d’œuvre étrangère'], redLines:['Nouvelle occupation étrangère'], partners:['USA','SAU','GBR'], rivals:['IRQ'] }),
  d({ id:'LBN', name:'Liban', flag:'🇱🇧', leader:'Émile Lahoud', regime:'République parlementaire confessionnelle', government:'Coalition confessionnelle', orientation:'transition', scale:31, gdp:17, population:3.5, growth:1.7, populationGrowth:1.4, inflation:0.4, unemployment:8, industry:15, openness:64, confidence:44, stability:36, security:37, interests:['Préserver la coexistence confessionnelle','Reconstruire les services'], vulnerabilities:['Dette publique','Système confessionnel','Influence syrienne'], redLines:['Guerre civile ou partition'], partners:['FRA','SYR'], rivals:['ISR'] }),
  d({ id:'LUX', name:'Luxembourg', flag:'🇱🇺', leader:'Jean-Claude Juncker', regime:'Monarchie parlementaire', government:'Coalition CSV–DP', orientation:'liberal', scale:30, gdp:21, population:0.44, growth:8.5, populationGrowth:1.4, inflation:3.8, unemployment:2.5, industry:20, openness:100, confidence:95, stability:86, security:48, interests:['Préserver la place financière','Approfondir l’Union européenne'], vulnerabilities:['Dépendance aux services financiers','Petite taille'], redLines:['Remise en cause de l’euro'], partners:['BEL','DEU','FRA'], rivals:[] }),
  d({ id:'MAR', name:'Maroc', flag:'🇲🇦', leader:'Mohammed VI', regime:'Monarchie exécutive', government:'Palais et gouvernement d’alternance', orientation:'monarchy', scale:45, gdp:37, population:28.8, growth:1.8, populationGrowth:1.5, inflation:1.9, unemployment:13.9, industry:18, openness:49, confidence:58, stability:62, security:57, interests:['Préserver la monarchie','Développer les liens européens'], vulnerabilities:['Sécheresse','Chômage','Question du Sahara occidental'], redLines:['Remise en cause de la monarchie ou du Sahara'], partners:['FRA','ESP','USA'], rivals:['DZA'] }),
  d({ id:'MEX', name:'Mexique', flag:'🇲🇽', leader:'Ernesto Zedillo', regime:'République fédérale en ouverture démocratique', government:'PRI en transition', orientation:'transition', scale:63, gdp:707, population:98.9, growth:6.6, populationGrowth:1.4, inflation:9.5, unemployment:2.6, industry:28, openness:70, confidence:76, stability:58, security:48, interests:['Consolider la transition démocratique','Approfondir l’intégration nord-américaine'], vulnerabilities:['Dépendance américaine','Inégalités','Violence criminelle'], redLines:['Perte de souveraineté économique'], partners:['USA','CAN','ESP'], rivals:[] }),
  d({ id:'MMR', name:'Myanmar', flag:'🇲🇲', leader:'Than Shwe', regime:'Junte militaire', government:'Conseil d’État pour la paix et le développement', orientation:'military', scale:35, gdp:8, population:45.2, growth:13.7, populationGrowth:1.3, inflation:-0.1, unemployment:5, industry:22, openness:24, confidence:30, stability:31, security:50, interests:['Préserver le contrôle militaire','Exploiter les ressources'], vulnerabilities:['Sanctions','Conflits ethniques','Isolement'], redLines:['Perte du pouvoir militaire'], partners:['CHN','THA'], rivals:[] }),
  d({ id:'MYS', name:'Malaisie', flag:'🇲🇾', leader:'Mahathir Mohamad', regime:'Monarchie fédérale parlementaire contrôlée', government:'Barisan Nasional', orientation:'nationalist', scale:47, gdp:93, population:23.2, growth:8.7, populationGrowth:2.1, inflation:1.5, unemployment:3.1, industry:30, openness:76, confidence:69, stability:62, security:59, interests:['Préserver l’équilibre interethnique','Attirer les industries exportatrices'], vulnerabilities:['Dette privée','Tensions interethniques','Dépendance aux exportations'], redLines:['Violence intercommunautaire'], partners:['SGP','JPN','CHN'], rivals:[] }),
  d({ id:'NLD', name:'Pays-Bas', flag:'🇳🇱', leader:'Wim Kok', regime:'Monarchie parlementaire', government:'Coalition violette', orientation:'liberal', scale:50, gdp:417, population:15.9, growth:4.2, populationGrowth:0.6, inflation:2.3, unemployment:3.8, industry:23, openness:96, confidence:93, stability:77, security:61, interests:['Préserver le commerce mondial','Renforcer l’Union européenne'], vulnerabilities:['Dépendance au commerce','Pression migratoire','Exposition financière'], redLines:['Blocage du marché unique'], partners:['DEU','BEL','GBR'], rivals:[] }),
  d({ id:'NZL', name:'Nouvelle-Zélande', flag:'🇳🇿', leader:'Helen Clark', regime:'Monarchie parlementaire', government:'Gouvernement travailliste', orientation:'social', scale:35, gdp:52, population:3.9, growth:3.8, populationGrowth:0.8, inflation:2.1, unemployment:6.1, industry:19, openness:66, confidence:88, stability:79, security:53, interests:['Préserver l’autonomie régionale','Sécuriser les exportations agricoles'], vulnerabilities:['Éloignement','Dépendance agricole','Vulnérabilité climatique'], redLines:['Abandon du contrôle maritime'], partners:['AUS','USA','GBR'], rivals:[] }),
  d({ id:'NGA', name:'Nigeria', flag:'🇳🇬', leader:'Olusegun Obasanjo', regime:'République fédérale en démocratisation', government:'Parti démocratique du peuple', orientation:'transition', scale:48, gdp:46, population:122.4, growth:5.4, populationGrowth:2.5, inflation:6.9, unemployment:4, industry:28, openness:42, confidence:47, stability:39, security:36, interests:['Consolider le fédéralisme','Monétiser le pétrole sans perdre le delta'], vulnerabilities:['Corruption','Tensions régionales','Dépendance pétrolière'], redLines:['Sécession ou coup d’État'], partners:['USA','GBR','ZAF'], rivals:[] }),
  d({ id:'NIC', name:'Nicaragua', flag:'🇳🇮', leader:'Arnoldo Alemán', regime:'République présidentielle', government:'Alliance libérale', orientation:'nationalist', scale:24, gdp:5, population:5.1, growth:5.5, populationGrowth:1.4, inflation:7.3, unemployment:10, industry:14, openness:40, confidence:45, stability:43, security:46, interests:['Consolider la paix civile','Attirer les investissements'], vulnerabilities:['Pauvreté','Institutions fragiles','Catastrophes naturelles'], redLines:['Retour à la guerre civile'], partners:['USA','MEX'], rivals:[] }),
  d({ id:'PAK', name:'Pakistan', flag:'🇵🇰', leader:'Pervez Musharraf', regime:'Régime militaire', government:'Conseil exécutif militaire', orientation:'military', scale:49, gdp:75, population:138.0, growth:4.3, populationGrowth:2.1, inflation:4.4, unemployment:7, industry:21, openness:36, confidence:43, stability:32, security:63, interests:['Préserver la parité stratégique avec l’Inde','Maintenir l’aide extérieure'], vulnerabilities:['Dette','Instabilité politique','Tensions indo-pakistanaises'], redLines:['Perte du Cachemire','Encerclement stratégique'], partners:['USA','CHN','SAU'], rivals:['IND'] }),
  d({ id:'PAN', name:'Panama', flag:'🇵🇦', leader:'Mireya Moscoso', regime:'République présidentielle', government:'Parti arnulfiste', orientation:'liberal', scale:28, gdp:12, population:2.9, growth:2.7, populationGrowth:1.7, inflation:1.5, unemployment:13, industry:17, openness:76, confidence:69, stability:61, security:45, interests:['Réussir la transition du canal','Devenir une plateforme logistique'], vulnerabilities:['Dépendance au canal','Inégalités','Petite économie'], redLines:['Perte de contrôle du canal'], partners:['USA','CRI','COL'], rivals:[] }),
  d({ id:'PER', name:'Pérou', flag:'🇵🇪', leader:'Alberto Fujimori', regime:'République présidentielle autoritaire', government:'Présidence Fujimori', orientation:'nationalist', scale:39, gdp:53, population:26.0, growth:3.0, populationGrowth:1.5, inflation:3.7, unemployment:8.5, industry:19, openness:47, confidence:52, stability:34, security:41, interests:['Préserver le contrôle présidentiel','Relancer les mines'], vulnerabilities:['Crise institutionnelle','Pauvreté','Dépendance minière'], redLines:['Insurrection armée'], partners:['USA','CHL'], rivals:[] }),
  d({ id:'PHL', name:'Philippines', flag:'🇵🇭', leader:'Joseph Estrada', regime:'République présidentielle', government:'Coalition de Laban', orientation:'transition', scale:43, gdp:81, population:76.0, growth:4.4, populationGrowth:2.1, inflation:4.0, unemployment:11, industry:20, openness:56, confidence:56, stability:42, security:39, interests:['Préserver l’alliance américaine','Réduire les insurrections'], vulnerabilities:['Pauvreté','Insurrections','Crise de gouvernance'], redLines:['Coup d’État ou partition'], partners:['USA','JPN'], rivals:[] }),
  d({ id:'PRT', name:'Portugal', flag:'🇵🇹', leader:'António Guterres', regime:'République parlementaire', government:'Parti socialiste', orientation:'social', scale:39, gdp:124, population:10.2, growth:3.8, populationGrowth:0.7, inflation:2.8, unemployment:4.4, industry:22, openness:70, confidence:82, stability:67, security:54, interests:['Consolider l’euro','Moderniser les infrastructures'], vulnerabilities:['Faible productivité','Endettement privé','Dépendance européenne'], redLines:['Sortie désordonnée de l’euro'], partners:['ESP','FRA','GBR'], rivals:[] }),
  d({ id:'QAT', name:'Qatar', flag:'🇶🇦', leader:'Hamad ben Khalifa Al Thani', regime:'Monarchie absolue', government:'Maison Al Thani', orientation:'monarchy', scale:33, gdp:17, population:0.59, growth:8.0, populationGrowth:4.0, inflation:2.0, unemployment:1.5, industry:48, openness:72, confidence:50, stability:67, security:62, interests:['Développer le gaz naturel','Préserver l’autonomie diplomatique'], vulnerabilities:['Dépendance aux hydrocarbures','Petite taille','Vulnérabilité régionale'], redLines:['Menace sur la dynastie'], partners:['USA','GBR'], rivals:['SAU','IRN'] }),
  d({ id:'ROU', name:'Roumanie', flag:'🇷🇴', leader:'Emil Constantinescu', regime:'République semi-présidentielle', government:'Coalition CDR', orientation:'transition', scale:39, gdp:37, population:22.4, growth:2.4, populationGrowth:-0.4, inflation:45.7, unemployment:11, industry:27, openness:49, confidence:60, stability:44, security:48, interests:['Préparer l’adhésion euro-atlantique','Réformer l’industrie'], vulnerabilities:['Inflation','Corruption','Déclin démographique'], redLines:['Retour dans l’orbite russe'], partners:['USA','FRA','HUN'], rivals:[] }),
  d({ id:'SRB', name:'Serbie', flag:'🇷🇸', leader:'Slobodan Milošević', regime:'République fédérale autoritaire sous sanctions', government:'Parti socialiste de Serbie', orientation:'nationalist', scale:36, gdp:7.3, population:7.5, growth:6.1, populationGrowth:-0.5, inflation:70, unemployment:13, industry:25, openness:30, confidence:31, stability:28, security:54, interests:['Préserver l’intégrité territoriale','Desserrer les sanctions'], vulnerabilities:['Sanctions','Défaite régionale','Économie dégradée'], redLines:['Indépendance du Kosovo'], partners:['RUS'], rivals:['USA','HRV'] }),
  d({ id:'SGP', name:'Singapour', flag:'🇸🇬', leader:'Goh Chok Tong', regime:'République parlementaire dominante', government:'Parti d’action populaire', orientation:'liberal', scale:45, gdp:96, population:4.0, growth:9.0, populationGrowth:1.8, inflation:1.4, unemployment:3.2, industry:36, openness:100, confidence:86, stability:84, security:73, interests:['Préserver le hub commercial','Maintenir la stabilité politique'], vulnerabilities:['Dépendance au commerce mondial','Vulnérabilité maritime','Vieillissement'], redLines:['Blocage du détroit de Malacca'], partners:['MYS','USA','JPN'], rivals:[] }),
  d({ id:'SDN', name:'Soudan', flag:'🇸🇩', leader:'Omar el-Béchir', regime:'République islamiste militaire', government:'Congrès national', orientation:'military', scale:34, gdp:12, population:29.5, growth:4.0, populationGrowth:2.6, inflation:8, unemployment:18, industry:17, openness:28, confidence:27, stability:22, security:28, interests:['Préserver le pouvoir central','Contrôler les ressources agricoles et pétrolières'], vulnerabilities:['Guerres périphériques','Isolement','Pauvreté'], redLines:['Sécession territoriale'], partners:['EGY','LBY'], rivals:['USA'] }),
  d({ id:'SWE', name:'Suède', flag:'🇸🇪', leader:'Göran Persson', regime:'Monarchie parlementaire', government:'Parti social-démocrate', orientation:'social', scale:47, gdp:261, population:8.9, growth:4.5, populationGrowth:0.2, inflation:1.3, unemployment:5.7, industry:29, openness:78, confidence:94, stability:79, security:64, interests:['Préserver le modèle social','Maintenir une autonomie de défense'], vulnerabilities:['Vieillissement','Dépendance exportatrice','Hésitation européenne'], redLines:['Abandon de la neutralité sans mandat politique'], partners:['FIN','DEU','NOR'], rivals:[] }),
  d({ id:'SYR', name:'Syrie', flag:'🇸🇾', leader:'Hafez al-Assad', regime:'République baasiste autoritaire', government:'Parti Baas', orientation:'military', scale:41, gdp:19, population:16.4, growth:0.7, populationGrowth:2.5, inflation:-3.8, unemployment:12, industry:21, openness:31, confidence:34, stability:34, security:62, interests:['Récupérer le Golan','Préserver l’influence au Liban'], vulnerabilities:['Isolement','Économie administrée','Succession politique'], redLines:['Reconnaissance de l’annexion du Golan'], partners:['IRN','RUS','LBN'], rivals:['ISR','USA'] }),
  d({ id:'THA', name:'Thaïlande', flag:'🇹🇭', leader:'Chuan Leekpai', regime:'Monarchie constitutionnelle parlementaire', government:'Coalition démocrate', orientation:'liberal', scale:49, gdp:126, population:62.9, growth:4.8, populationGrowth:0.9, inflation:1.6, unemployment:2.4, industry:30, openness:65, confidence:68, stability:54, security:49, interests:['Relancer l’économie asiatique','Préserver la monarchie'], vulnerabilities:['Dette privée','Inégalités régionales','Risque de coup'], redLines:['Atteinte à la monarchie'], partners:['USA','JPN','MYS'], rivals:[] }),
  d({ id:'TKM', name:'Turkménistan', flag:'🇹🇲', leader:'Saparmurat Niyazov', regime:'Présidence personnelle autoritaire', government:'Parti démocratique du Turkménistan', orientation:'party_state', scale:28, gdp:2.9, population:4.5, growth:5.5, populationGrowth:1.4, inflation:8, unemployment:15, industry:39, openness:26, confidence:24, stability:40, security:53, interests:['Monétiser le gaz','Préserver la neutralité proclamée'], vulnerabilities:['Personnalisation du pouvoir','Dépendance gazière','Enclavement'], redLines:['Intervention étrangère'], partners:['RUS','IRN'], rivals:[] }),
  d({ id:'TUN', name:'Tunisie', flag:'🇹🇳', leader:'Zine el-Abidine Ben Ali', regime:'République présidentielle autoritaire', government:'Rassemblement constitutionnel démocratique', orientation:'party_state', scale:36, gdp:21, population:9.6, growth:4.7, populationGrowth:1.1, inflation:2.8, unemployment:15.7, industry:25, openness:61, confidence:61, stability:56, security:58, interests:['Préserver la stabilité autoritaire','Développer les liens européens'], vulnerabilities:['Chômage diplômé','Dépendance touristique','Répression politique'], redLines:['Menace directe sur le régime'], partners:['FRA','ITA'], rivals:[] }),
  d({ id:'TWN', name:'Taïwan', flag:'🇹🇼', leader:'Lee Teng-hui', regime:'République semi-présidentielle démocratique', government:'Kuomintang en transition électorale', orientation:'liberal', scale:61, gdp:331, population:22.3, growth:5.8, populationGrowth:0.7, inflation:1.3, unemployment:3.0, industry:31, openness:90, confidence:84, stability:68, security:74, interests:['Préserver le statu quo dans le détroit','Consolider la base technologique'], vulnerabilities:['Pression militaire chinoise','Dépendance commerciale extérieure','Exposition aux semi-conducteurs'], redLines:['Annexion ou coercition militaire'], partners:['USA','JPN'], rivals:['CHN'] }),
  d({ id:'UKR', name:'Ukraine', flag:'🇺🇦', leader:'Leonid Koutchma', regime:'République semi-présidentielle', government:'Présidence et oligarchies régionales', orientation:'nationalist', scale:46, gdp:31, population:49.2, growth:5.9, populationGrowth:-0.7, inflation:28.2, unemployment:11.7, industry:32, openness:46, confidence:43, stability:38, security:48, interests:['Préserver la souveraineté','Équilibrer Russie et Europe'], vulnerabilities:['Déclin démographique','Industrie obsolète','Dépendance énergétique russe'], redLines:['Partition territoriale'], partners:['POL','RUS','DEU'], rivals:[] }),
  d({ id:'URY', name:'Uruguay', flag:'🇺🇾', leader:'Jorge Batlle', regime:'République présidentielle', government:'Coalition Colorado–Blanco', orientation:'liberal', scale:29, gdp:23, population:3.3, growth:-1.9, populationGrowth:0.7, inflation:4.8, unemployment:13.6, industry:18, openness:52, confidence:75, stability:71, security:55, interests:['Préserver la stabilité démocratique','Maintenir l’accès aux marchés du Mercosur'], vulnerabilities:['Dépendance régionale','Récession','Petite taille'], redLines:['Rupture du Mercosur'], partners:['ARG','BRA'], rivals:[] }),
  d({ id:'UZB', name:'Ouzbékistan', flag:'🇺🇿', leader:'Islam Karimov', regime:'République présidentielle autoritaire', government:'Présidence et appareil sécuritaire', orientation:'party_state', scale:36, gdp:13, population:24.8, growth:4.0, populationGrowth:1.4, inflation:25, unemployment:10, industry:26, openness:28, confidence:34, stability:42, security:60, interests:['Préserver le contrôle régional','Développer coton et énergie'], vulnerabilities:['Autoritarisme','Enclavement','Tensions islamistes'], redLines:['Islamisme armé ou sécession'], partners:['RUS','KAZ'], rivals:['AFG'] }),
  d({ id:'VEN', name:'Venezuela', flag:'🇻🇪', leader:'Hugo Chávez', regime:'République présidentielle en rupture', government:'Révolution bolivarienne naissante', orientation:'nationalist', scale:47, gdp:117, population:24.3, growth:3.7, populationGrowth:1.7, inflation:13.4, unemployment:13.9, industry:26, openness:44, confidence:52, stability:38, security:47, interests:['Récupérer la rente pétrolière','Refonder l’État autour du pouvoir exécutif'], vulnerabilities:['Dépendance pétrolière','Polarisation sociale','Institutions fragiles'], redLines:['Renversement de la révolution bolivarienne'], partners:['CUB','BRA'], rivals:['USA'] }),
  d({ id:'YEM', name:'Yémen', flag:'🇾🇪', leader:'Ali Abdullah Saleh', regime:'République présidentielle autoritaire', government:'Congrès général du peuple', orientation:'nationalist', scale:28, gdp:9, population:18.1, growth:5.5, populationGrowth:3.5, inflation:4, unemployment:35, industry:19, openness:33, confidence:27, stability:25, security:31, interests:['Préserver l’unité nationale','Développer les hydrocarbures'], vulnerabilities:['Pauvreté','Tribus armées','Ressources hydriques limitées'], redLines:['Sécession du Sud'], partners:['SAU','USA'], rivals:[] }),
  d({ id:'ZWE', name:'Zimbabwe', flag:'🇿🇼', leader:'Robert Mugabe', regime:'République présidentielle autoritaire', government:'ZANU-PF', orientation:'nationalist', scale:32, gdp:6, population:11.9, growth:-3.1, populationGrowth:1.0, inflation:55.9, unemployment:20, industry:25, openness:42, confidence:34, stability:31, security:36, interests:['Préserver le pouvoir','Contrôler les terres et les minerais'], vulnerabilities:['Crise agraire','Isolement','Érosion monétaire'], redLines:['Perte du pouvoir de la ZANU-PF'], partners:['ZAF','COD'], rivals:['GBR'] }),
  d({ id:'MOZ', name:'Mozambique', flag:'🇲🇿', leader:'Joaquim Chissano', regime:'République présidentielle', government:'FRELIMO', orientation:'social', scale:26, gdp:5.9, population:18.2, growth:0.8, populationGrowth:2.4, inflation:12.7, unemployment:23, industry:13, openness:38, confidence:42, stability:49, security:43, interests:['Reconstruire après la guerre','Attirer les infrastructures étrangères'], vulnerabilities:['Pauvreté','Dépendance à l’aide','Catastrophes climatiques'], redLines:['Retour à la guerre civile'], partners:['ZAF','PRT'], rivals:[] }),
  d({ id:'TZA', name:'Tanzanie', flag:'🇹🇿', leader:'Benjamin Mkapa', regime:'République présidentielle', government:'Chama Cha Mapinduzi', orientation:'social', scale:29, gdp:10, population:34.0, growth:4.9, populationGrowth:2.5, inflation:6, unemployment:5, industry:15, openness:34, confidence:48, stability:57, security:47, interests:['Préserver l’unité nationale','Développer les infrastructures'], vulnerabilities:['Pauvreté rurale','Dépendance à l’aide','Faible industrialisation'], redLines:['Sécession de Zanzibar'], partners:['KEN','ZAF'], rivals:[] }),
  d({ id:'SEN', name:'Sénégal', flag:'🇸🇳', leader:'Abdou Diouf', regime:'République présidentielle démocratique', government:'Parti socialiste', orientation:'social', scale:28, gdp:6, population:9.5, growth:5.1, populationGrowth:2.6, inflation:0.7, unemployment:12, industry:14, openness:44, confidence:60, stability:61, security:50, interests:['Préserver la stabilité démocratique','Consolider l’UEMOA'], vulnerabilities:['Pauvreté','Sécheresse','Dépendance aux importations'], redLines:['Conflit séparatiste généralisé'], partners:['FRA','CIV','MLI'], rivals:[] }),
  d({ id:'CIV', name:'Côte d’Ivoire', flag:'🇨🇮', leader:'Laurent Gbagbo', regime:'République présidentielle contestée', government:'Front populaire ivoirien', orientation:'nationalist', scale:31, gdp:16.6, population:16.0, growth:-0.3, populationGrowth:2.2, inflation:2.5, unemployment:12, industry:18, openness:48, confidence:42, stability:37, security:39, interests:['Préserver la primauté d’Abidjan','Développer cacao et pétrole'], vulnerabilities:['Tensions identitaires','Dépendance au cacao','Instabilité militaire'], redLines:['Partition du pays'], partners:['FRA','SEN'], rivals:[] }),
  d({ id:'CMR', name:'Cameroun', flag:'🇨🇲', leader:'Paul Biya', regime:'République présidentielle autoritaire', government:'Rassemblement démocratique du peuple camerounais', orientation:'party_state', scale:32, gdp:9, population:15.0, growth:4.2, populationGrowth:2.7, inflation:1.2, unemployment:8, industry:17, openness:36, confidence:40, stability:42, security:39, interests:['Préserver l’unité nationale','Maintenir l’appareil d’État'], vulnerabilities:['Corruption','Inégalités régionales','Faible diversification'], redLines:['Sécession anglophone'], partners:['FRA','NGA'], rivals:[] }),
  d({ id:'UGA', name:'Ouganda', flag:'🇺🇬', leader:'Yoweri Museveni', regime:'République présidentielle à mouvement dominant', government:'Mouvement de résistance nationale', orientation:'military', scale:30, gdp:6, population:23.5, growth:3.1, populationGrowth:3.2, inflation:3.4, unemployment:7, industry:13, openness:31, confidence:38, stability:37, security:35, interests:['Préserver le régime','Projeter une influence dans les Grands Lacs'], vulnerabilities:['Pauvreté','Conflit régional','Dépendance à l’aide'], redLines:['Renversement du pouvoir'], partners:['USA','RWA','KEN'], rivals:['COD','SDN'] }),
  d({ id:'KHM', name:'Cambodge', flag:'🇰🇭', leader:'Hun Sen', regime:'Monarchie constitutionnelle à parti dominant', government:'Parti du peuple cambodgien', orientation:'party_state', scale:26, gdp:4, population:12.2, growth:10.0, populationGrowth:1.6, inflation:-0.8, unemployment:2.5, industry:14, openness:48, confidence:38, stability:43, security:45, interests:['Consolider le pouvoir','Développer le textile et l’aide asiatique'], vulnerabilities:['Pauvreté','Dépendance aux investisseurs','Institutions faibles'], redLines:['Retour à la guerre civile'], partners:['VNM','CHN','THA'], rivals:[] }),
];

/**
 * Harmonisation des séries qui alimentent le macro-moteur.
 *
 * Les fiches compactes avaient mélangé, pour quelques pays, chômage déclaré
 * et sous-emploi estimé. Le moteur attend ici le taux harmonisé comparable
 * d'une économie à l'autre ; la pression sociale et l'informalité restent
 * portées par stabilité, industrie et vulnérabilités, pas par un faux taux de
 * chômage officiel. Les valeurs sont arrondies à deux décimales.
 */
const harmonized2000: Record<string, Partial<Pick<NationalBaselineDescriptor, 'unemployment' | 'industry' | 'populationGrowth'>>> = {
  AFG: { unemployment: 7.90 }, AGO: { unemployment: 16.65 }, BHR: { unemployment: 1.08 },
  BLR: { unemployment: 12.19 }, BIH: { unemployment: 25.45 }, BOL: { unemployment: 2.44 },
  COD: { unemployment: 3.25 }, DOM: { unemployment: 6.43 }, ECU: { unemployment: 4.80 },
  ETH: { unemployment: 3.50 }, GTM: { unemployment: 2.14 }, IRQ: { unemployment: 8.04, industry: 84.80 },
  KEN: { unemployment: 2.88 }, KWT: { unemployment: 0.80 }, MMR: { unemployment: 0.71, industry: 9.69 },
  PAK: { unemployment: 0.61 }, PAN: { unemployment: 6.19 }, PER: { unemployment: 4.96 },
  PHL: { unemployment: 3.77 }, QAT: { unemployment: 0.87 }, ROU: { unemployment: 6.97, populationGrowth: -0.13 },
  YEM: { unemployment: 11.56, industry: 48.78 }, ZWE: { unemployment: 5.68 }, MOZ: { unemployment: 2.83 },
  TZA: { unemployment: 3.13 }, SEN: { unemployment: 2.64 }, CIV: { unemployment: 4.83 },
  UGA: { unemployment: 3.53 }, KHM: { unemployment: 0.74 },
  BGR: { populationGrowth: -0.49 }, CZE: { populationGrowth: -0.28 }, HRV: { populationGrowth: -0.99 },
  SRB: { populationGrowth: -0.32 }, URY: { populationGrowth: 0.37 },
};

for (const descriptor of nationalBaseline2000) {
  const correction = harmonized2000[descriptor.id];
  if (correction) Object.assign(descriptor, correction);
}

const capacities = (descriptor: NationalBaselineDescriptor): CapacityState => {
  const base = Math.min(92, 32 + descriptor.scale * 0.75);
  const admin = Math.min(95, base + (descriptor.orientation === 'party_state' || descriptor.orientation === 'military' ? 8 : 0));
  return {
    government: { maximum: Math.round(base + 4), committed: Math.round(base * 0.48) },
    administration: { maximum: Math.round(admin), committed: Math.round(admin * 0.52) },
    diplomacy: { maximum: Math.round(base + (descriptor.openness > 65 ? 10 : 0)), committed: Math.round(base * 0.42) },
    economy: { maximum: Math.round(base + descriptor.industry * 0.12), committed: Math.round(base * 0.56) },
    intelligence: { maximum: Math.round(base + descriptor.security * 0.12), committed: Math.round(base * 0.45) },
    defense: { maximum: Math.round(base + descriptor.security * 0.15), committed: Math.round(base * 0.58) },
  };
};

const doctrine = (orientation: NationalBaselineDescriptor['orientation']) => ({
  liberal: { economic: 30, social: -4, sovereignty: 28, security: 22 },
  social: { economic: 4, social: 30, sovereignty: 16, security: 16 },
  nationalist: { economic: 8, social: 0, sovereignty: 58, security: 52 },
  party_state: { economic: 12, social: -20, sovereignty: 76, security: 66 },
  military: { economic: 4, social: -8, sovereignty: 72, security: 82 },
  monarchy: { economic: 18, social: -38, sovereignty: 58, security: 62 },
  theocratic: { economic: -4, social: -58, sovereignty: 82, security: 76 },
  fragile: { economic: 0, social: 14, sovereignty: 42, security: 42 },
  transition: { economic: 18, social: 14, sovereignty: 32, security: 34 },
}[orientation]);

export function createNationalBaselineCountries2000(): Record<string, CountryState> {
  return Object.fromEntries(nationalBaseline2000.map((descriptor) => {
    const d = doctrine(descriptor.orientation);
    const goal = descriptor.interests[0] ?? 'Préserver la stabilité nationale';
    const goal2 = descriptor.interests[1];
    const seats = descriptor.scale >= 55 ? 500 : descriptor.scale >= 35 ? 300 : 180;
    const governingSeats = descriptor.orientation === 'transition' || descriptor.orientation === 'liberal' ? Math.round(seats * 0.53) : Math.round(seats * 0.72);
    return [descriptor.id, {
      id: descriptor.id, name: descriptor.name, flag: descriptor.flag, weight: descriptor.scale, statisticalReliability: descriptor.confidence,
      metrics: { budget: Math.max(18, Math.round(descriptor.gdp * 0.17)), industry: descriptor.industry, stability: descriptor.stability, security: descriptor.security },
      capacities: capacities(descriptor),
      politics: {
        regime: descriptor.regime, executive: descriptor.leader, headOfGovernment: descriptor.leader, governmentLabel: descriptor.government,
        legislatureSeats: seats, governingSeats, publicApproval: Math.round((descriptor.stability + descriptor.security) / 2), administrativeCompliance: Math.round(Math.min(92, descriptor.stability + (descriptor.orientation === 'party_state' ? 18 : 4))), doctrine: d,
      },
      strategy: {
        goals: [goal, ...(goal2 ? [goal2] : [])].map((label, index) => ({ id: `${descriptor.id.toLowerCase()}-goal-${index + 1}`, label, priority: index === 0 ? 88 : 72, progress: 35, status: 'active' as const })),
        vulnerabilities: descriptor.vulnerabilities, redLines: descriptor.redLines, partners: descriptor.partners, rivals: descriptor.rivals, lastReviewDate: '2000-01-01',
      },
    } satisfies CountryState];
  }));
}
